### ISSUE TITLE
Automate updating the lat and longs of new GTFS bus stops

### ISSUE THREAD

**Issue by brendanbabb** [codeforanchorage/realtime-bus-sms#105]

**Comment by markmeyerphoto** [comment]
I think I have a nice solutions for this, but there are a couple wrinkles I'm not sure how to handle.

I made a bash script that:
1. Uses `curl -z` to get the GTFS .zip file, but only if it has changed
2. Unzips it into the raw directory
3. Runs the Ruby convert scripts to create the geoJSON files
4. Sends a Posix signal to the running node app to tell it to reload the files

In node we can listen for the signal and invalidate/reload the require cache with something like:
`delete require.cache[require.resolve('../gtfs/geojson/stops.json')]`

I have this working locally (I think). The things I'm not sure how to do on the AWS side are:
1. How to get the running Node PID in order to send the signal. (Maybe PM2 can give them to us?)
2. Make the script run on a schedule. 
3. Get all the paths right for the locations of scripts  — that should be easy.

I'll bring it in to Hack Night.

**Comment by brendanbabb** [comment]
Mark,

Sounds good. I think the routes.rb creates some big files and I am not sure
if we use it, so we might be able to ignore that one. We also need a script
to take the stops.txt file and create the /lib/stop_number_lookup.js This
would just consist of changing the txt csv file into a json file with the
mappings.

Brendan

**Comment by brendanbabb** [comment]
@markmeyerphoto mentioned this works locally on his machine but is not picking up the changed GTFS file on AWS. Is this related to PM2?

**Comment by markmeyerphoto** [comment]
This has been changed and should be updating GTFS daily.
