### ISSUE TITLE
Promotion

### ISSUE THREAD

**Issue by NigelKibodeaux** [codeforanchorage/realtime-bus-sms#19]
Not a technical thing, but I'd like to get (removable?) stickers or magnets to put on bus stops. There are a lot of places online that can do this for fairly cheap. Maybe we can work this out at the next meeting.

**Comment by brendanbabb** [comment]
Sounds good. We should make sure to coordinate with People Mover, since I think it is technically there property and they don't want just anyone attaching flyers to the bus stops, but I think they would be up for it. I am still working on getting the Twilio number transferred over to CfA. Trying to track down the right Account ids and people being out of office has slowed it down.

**Comment by NigelKibodeaux** [comment]
we're on the bus stops now!
